export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROJECTS = 'GET_PROJECTS';
export const SET_PROJECTS = 'SET_PROJECTS';
export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const SET_PROJECT = 'SET_PROJECT';
export const REQUEST_PROJECT = 'REQUEST_PROJECT';
