export const CLEAR_STATE = 'CLEAR_STATE';

export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_ACTIVE_DASHBOARD_COMPONENT = 'SET_ACTIVE_DASHBOARD_COMPONENT';

export const GET_PROJECTS = 'GET_PROJECTS';
export const SET_PROJECTS = 'SET_PROJECTS';
export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';

export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
export const SET_PROJECT = 'SET_PROJECT';
export const REQUEST_PROJECT = 'REQUEST_PROJECT';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PAGE = 'SET_PAGE';
export const REQUEST_PAGE = 'REQUEST_PAGE';

export const SET_CURRENT_TEST = 'SET_CURRENT_TEST';
export const SET_TEST = 'SET_TEST';
export const REQUEST_TEST = 'REQUEST_TEST';
